name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - name: Publish to WinGet on Snapmaker/Luban package
        if: ${{ github.repository == 'Snapmaker/Luban' }}
        uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: SnapmakerDevTeam.SnapmakerLuban
          installers-regex: 'x64.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: jane-rose
